### ISSUE TITLE
Problems with theme

### ISSUE THREAD

**Issue by Sorebit** [rehanhaider/pelican-to-github-pages#1]
There seems to be a problem with theme support.
My theme is currently in the `/theme` directory, with `pelicanconf.py` file also pointing to it.

```
Building site 👷 
WARNING: Empty theme folder. Using `basic` theme.
```

Is it perhaps connected to the fact, that my theme is a submodule? Does the action clone submodules?

**Comment by rehanhaider** [comment]
Can you paste the contents of pelicanconf.py & publishconf.py files

**Comment by Sorebit** [comment]
Sure, I'm only using `pelicanconf.py`, though.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*- #

SITENAME = 'sorebit'
SITEURL = ''

PATH = 'content'
TIMEZONE = 'Europe/Warsaw'
DEFAULT_DATE_FORMAT = ('%B %d, %Y')
DEFAULT_LANG = 'en'
THEME = 'theme'
# Static files
STATIC_PATHS = ['images', 'pdfs', 'files']

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Articles
ARTICLE_PATHS = ['articles']
ARTICLE_URL = '{category}/{slug}.html'
ARTICLE_SAVE_AS = '{category}/{slug}.html'
# Pages
PAGE_PATHS = ['pages']
PAGE_URL = '{slug}.html'
PAGE_SAVE_AS = '{slug}.html'
# Disable tags and authors
TAGS_SAVE_AS = ''
TAG_SAVE_AS = ''
AUTHORS_SAVE_AS = ''
AUTHOR_SAVE_AS = ''

# Categories URL names are the same as directory for articles in this category.
CATEGORY_URL = '/{slug}.html'
CATEGORY_SAVE_AS = '/{slug}.html'
CATEGORIES_SAVE_AS = ''  # Disable `/categories.html` page
USE_FOLDER_AS_CATEGORY = True
# TODO: Consider archives

# Default to draft
DEFAULT_METADATA = {
    'status': 'draft',
}

DEFAULT_PAGINATION = 10

# Plugins https://github.com/getpelican/pelican-plugins
PLUGINS = None
```

**Comment by Sorebit** [comment]
I'm pretty sure, this has to do with not cloning submodules

**Comment by rehanhaider** [comment]
> I'm pretty sure, this has to do with not cloning submodules

You are absolutely correct. Cloning the repository is not cloning the submodule. This should be an easy fix though, thanks for pointing it out. 

If you want just change the clone statement in `entrypoint.sh` to recursively clone and send the PR, otherwise I can fix sometime later.

**Comment by rehanhaider** [comment]
@Sorebit Change your `pelican.yaml` to below to enable cloning of submodules as well
```yaml
name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - uses: rehanhaider/pelican-to-github-pages@v1.0.3
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
```
